### PR TITLE
fix: make sure annotated endpoints works along Vaadin PUSH

### LINKED ISSUE #78: Enabling "Push" functionality breaks annotated websocket servers
The solution in #69 is intended to trigger [this line](https://github.com/quarkusio/quarkus/blob/505770c3c3b89507f2f97ef9a5e0b32f029e3239/extensions/websockets/client/runtime/src/main/java/io/quarkus/websockets/client/runtime/WebsocketCoreRecorder.java#L73) so that Quarkus knows that websockets are used. Unfortunately, [this conditional](https://github.com/quarkusio/quarkus/blob/505770c3c3b89507f2f97ef9a5e0b32f029e3239/extensions/websockets/client/runtime/src/main/java/io/quarkus/websockets/client/runtime/WebsocketCoreRecorder.java#L83) forces the builder to _ignore_ any annotated server classes that are not also referenced by a config class (such as, but not limited to, the `EnableWebsockets` one). Therefore, if you have an annotated server class without also including a config class for it, quarkus drops your server from the build.

I can't do this myself here, but I've found a few breadcrumbs that might help with fixing it:

* [here](https://github.com/quarkusio/quarkus/blob/505770c3c3b89507f2f97ef9a5e0b32f029e3239/extensions/websockets/server/deployment/src/main/java/io/quarkus/websockets/deployment/ServerWebSocketProcessor.java#L41) is where server annotated endpoints are discovered
* [here](https://github.com/quarkusio/quarkus/blob/505770c3c3b89507f2f97ef9a5e0b32f029e3239/extensions/websockets/client/deployment/src/main/java/io/quarkus/websockets/client/deployment/WebsocketClientProcessor.java#L87) is where those are used
* it should be sufficient to produce an annotated endpoint builditem pointing to the atmosphere handler, to get the same result as `EnableWebsockets`

### PR DESCRIPTION
**Pull request by mcollovati**
## Description

The workaround added to make PUSH work in Quarkus prevents the usage of custom annotated websocket endpoint. This change allows them to work along Vaadin PUSH.

Fixes #78

## Type of change

- [X] Bugfix
- [ ] Feature

## Checklist

- [X] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [X] I have added a description following the guideline.
- [X] The issue is created in the corresponding repository and I have referenced it.
- [X] I have added tests to ensure my change is effective and works as intended.
- [X] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

**Review by MarcinVaadin — DISMISSED** [review]
Great that we now have covered custom web sockets with tests also on Quarkus. I've committed proposed changes to Flow, after releasing Flow with https://github.com/vaadin/flow/pull/14694 we could remove `JSR356_PATH_MAPPING_LENGTH` from Quarkus.

**Review by mshabarov — DISMISSED** [review]

**Comment by mcollovati** [comment]
Update the PR to be compatible with Vaadin 24. @MarcinVaadin @mshabarov Please review it again to check if it is all ok

File: deployment/src/main/java/com/vaadin/quarkus/deployment/VaadinQuarkusProcessor.java [hunk 1]
```diff
@@ -144,7 +145,11 @@ void mapVaadinServletPaths(final BeanArchiveIndexBuildItem beanArchiveIndex,
                     .builder(QuarkusVaadinServlet.class.getName(),
                             QuarkusVaadinServlet.class.getName())
                     .addMapping("/*").setAsyncSupported(true)
-                    .setLoadOnStartup(1).build());
+                    .setLoadOnStartup(1)
+                    // TODO: should be fixed in Flow and removed from here
+                    .addInitParam(ApplicationConfig.JSR356_PATH_MAPPING_LENGTH,
```
Comment (mshabarov) [inline deployment/src/main/java/com/vaadin/quarkus/deployment/VaadinQuarkusProcessor.java:150]: Do still need this parameter? Flow's PushRequestHandler now sets it already.

Comment (mcollovati) [reply deployment/src/main/java/com/vaadin/quarkus/deployment/VaadinQuarkusProcessor.java:150]: Good catch! I'll remove it

Comment (mcollovati) [reply deployment/src/main/java/com/vaadin/quarkus/deployment/VaadinQuarkusProcessor.java]: done

**Review by mshabarov — APPROVED** [review]
