### PR TITLE
Skip user `VaadinServlet`s without @WebServlet instead of NPE on `quarkusBuild`

### LINKED ISSUE #76: NPE on quarkusBuild if VaadinServlet present in classpath without @WebServlet annotation
For example if `vaadin-cdi` happen to be present in classpath `VaadinQuarkusProcessor` finds `CdiVaadinServlet` and assumes it's an user provided `VaadinServlet` with build failing with confusing NPE.

```
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step com.vaadin.quarkus.deployment.VaadinQuarkusProcessor#mapVaadinServletPaths threw an exception: java.lang.NullPointerException: Cannot invoke "org.jboss.jandex.AnnotationInstance.value(String)" because "webServletInstance" is null
	at com.vaadin.quarkus.deployment.VaadinQuarkusProcessor.registerUserServlets(VaadinQuarkusProcessor.java:231)
	at com.vaadin.quarkus.deployment.VaadinQuarkusProcessor.mapVaadinServletPaths(VaadinQuarkusProcessor.java:127)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:925)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)

	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:330)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.reloadExistingApplication(AugmentActionImpl.java:265)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.reloadExistingApplication(AugmentActionImpl.java:60)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.restartApp(IsolatedDevModeMain.java:251)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.restartCallback(IsolatedDevModeMain.java:234)
	at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:536)
	at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:436)
	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$4.handle(VertxHttpHotReplacementSetup.java:152)
	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$4.handle(VertxHttpHotReplacementSetup.java:139)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step com.vaadin.quarkus.deployment.VaadinQuarkusProcessor#mapVaadinServletPaths threw an exception: java.lang.NullPointerException: Cannot invoke "org.jboss.jandex.AnnotationInstance.value(String)" because "webServletInstance" is null
	at com.vaadin.quarkus.deployment.VaadinQuarkusProcessor.registerUserServlets(VaadinQuarkusProcessor.java:231)
	at com.vaadin.quarkus.deployment.VaadinQuarkusProcessor.mapVaadinServletPaths(VaadinQuarkusProcessor.java:127)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:925)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)

	at io.quarkus.builder.Execution.run(Execution.java:116)
	at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:157)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:328)
	... 18 more
Caused by: java.lang.NullPointerException: Cannot invoke "org.jboss.jandex.AnnotationInstance.value(String)" because "webServletInstance" is null
	at com.vaadin.quarkus.deployment.VaadinQuarkusProcessor.registerUserServlets(VaadinQuarkusProcessor.java:231)
	at com.vaadin.quarkus.deployment.VaadinQuarkusProcessor.mapVaadinServletPaths(VaadinQuarkusProcessor.java:127)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:925)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

### PR DESCRIPTION
**Pull request by grossws**
## Description

If `VaadinServlet` without `@WebServlet` annotation present (like when `vaadin-cdi` happened to be in classpath) currently `quarkusBuild` will fail with NPE.

This patch skips such servlets with a warning in log.

Fixes #76

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

### CODE REVIEW

**Comment by mcollovati** [comment]
@grossws thanks for the contribution! Do you mind signing the CLA?

**Comment by grossws** [comment]
@mcollovati, I've signed CLA, feel free to merge.

File: deployment/src/main/java/com/vaadin/quarkus/deployment/VaadinQuarkusProcessor.java [hunk 1]
```diff
@@ -63,8 +63,11 @@
 import com.vaadin.quarkus.context.UIScopedContext;
 import com.vaadin.quarkus.context.VaadinServiceScopedContext;
 import com.vaadin.quarkus.context.VaadinSessionScopedContext;
+import org.slf4j.Logger;
+import org.slf4j.LoggerFactory;
 
 class VaadinQuarkusProcessor {
+    private static final Logger LOG = LoggerFactory.getLogger(VaadinQuarkusProcessor.class);
```
Comment (taefi) [inline deployment/src/main/java/com/vaadin/quarkus/deployment/VaadinQuarkusProcessor.java:70]:
```suggestion

    private static final Logger LOG = LoggerFactory.getLogger(VaadinQuarkusProcessor.class);
```

**Review by taefi — CHANGES_REQUESTED** [review]

**Review by taefi — APPROVED** [review]
