### PR TITLE
test: retry count assertion on session invalidation

### LINKED ISSUE #126: SessionContext ITs are flaky
```
Error:  Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 4.889 s <<< FAILURE! - in com.vaadin.flow.quarkus.it.SessionContextIT
Error:  com.vaadin.flow.quarkus.it.SessionContextIT.httpSessionCloseDestroysSessionContext  Time elapsed: 1.157 s  <<< FAILURE!
java.lang.AssertionError: expected:<1> but was:<0>
	at vaadin.quarkus.production.tests@1.1-SNAPSHOT/com.vaadin.flow.quarkus.it.SessionContextIT.assertDestroyCountEquals(SessionContextIT.java:86)
	at vaadin.quarkus.production.tests@1.1-SNAPSHOT/com.vaadin.flow.quarkus.it.SessionContextIT.httpSessionCloseDestroysSessionContext(SessionContextIT.java:54)
```

### PR DESCRIPTION
**Pull request by mcollovati**
## Description

Session context tests check the counter value hold by a session bean right after invalidating the Vaadin session. Since the counter is incremented in the PreDestroy hook, it may happen that when the test checks for the counter value, the callback has not yet been invoked. This change retries the counter check for at most on second, to preven ttest flakyness.

Fixes #126

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

File: integration-tests/common-test-code/src/test/java/com/vaadin/flow/quarkus/it/AbstractCdiIT.java [hunk 1]
```diff
@@ -41,6 +41,17 @@ protected String getText(String id) {
         return findElement(By.id(id)).getText();
     }
 
+    protected void waitForCount(int expectedCount, String counter) {
+        waitUntil(driver -> {
+            try {
+                assertCountEquals(expectedCount, counter);
+                return true;
```
Comment (czp13) [inline integration-tests/common-test-code/src/test/java/com/vaadin/flow/quarkus/it/AbstractCdiIT.java:48]: not sure if the return values are matters, so not sure when an exception happens, then it is false, then we do not return the type, because it is void... So basically we swallow the exception and pass the test in the end...

maybe 

```java
    protected boolean waitForCount(int expectedCount, String counter) {
       return waitUntil(driver -> {
            try {
                assertCountEquals(expectedCount, counter);
                return true;
                            } catch (Exception ex) {
                return false;
            }
        }, 1);
    }
    
    and then:
    ```
    assertTrue(waitForCount(expectedCount, DESTROY_COUNT));
    ```

What do you think? Maybe exceptions will never happen in that case it is safer and no swallowed false positive test happens.

Comment (mcollovati) [reply integration-tests/common-test-code/src/test/java/com/vaadin/flow/quarkus/it/AbstractCdiIT.java:48]: The return value is used by the waitUntil function. If, after a timeout, the lambda still return false (or null) waitUntil will throw an exception.
So in this case the assertion on return value is not useful for the test

Comment (czp13) [reply integration-tests/common-test-code/src/test/java/com/vaadin/flow/quarkus/it/AbstractCdiIT.java:48]: 👍 ok, so we will have an exception in the case I was referring to, fair enough! thanks.

**Review by czp13 — APPROVED** [review]
